spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapis?useUnicode=true&characterEncoding=utf8
    username: root
    password: buyaosong123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:static/mybatis/mybatis-config.xml
  mapper-locations: classpath:static/mybatis/mapper/*.xml



